### ISSUE TITLE
Prefer Brotli over Gzip

### ISSUE THREAD

**Issue by leebenson** [koajs/send#83]
I see that Brotli was released in v4.1.0 - awesome, thanks for adding!

There's one small issue. Chrome's typical `Accept-Encoding` header looks like this:

`Accept-Encoding:gzip, deflate, sdch, br`

It seems that koa-send interprets the order as a preference, and if it sees gzip, serves that first. That means if both `.gz` and `.br` files are available, the Brotli variants will never get sent:

<img width="1061" alt="screen shot 2017-05-30 at 13 20 14" src="https://cloud.githubusercontent.com/assets/719722/26583043/708d4562-453b-11e7-86bb-3989511f0213.png">

In instances where more than one compression algorithm is accepted, I think it'd be better to automatically send the _smallest_ file.

**Comment by jtmthf** [comment]
@leebenson In the bottom example you have `gzip, bz`, instead of `gzip, br`. Perhaps that is the issue faced. In the tests I didn't explicitly test for different orders, but it should send back the brotli version always if requested and available.

**Comment by leebenson** [comment]
@jtmthf - yes, exactly. To be clear, the ordering of the second example was intentional to highlight it being the issue. Chrome (at least my local installation) seems to always list `gzip` first, meaning the Brotli version of any file would never get sent.

IMO, the best future-proof solution would be to read the `Accept-Encoding` header, stat each file type that's available into an array, and then `reduce()` the filesize using a 'smallest' comparison. That way, the user will always get back the smallest file type that's supported.

Always preferring Brotli over Gzip would probably also have the same effect, practically (I don't know if it's technical ever possible for gzip to bear Brotli, filesize-wise), but if/when the next algo comes along, a reduction routine that serves the smallest file wouldn't need amending.

Thanks @jtmthf. I didn't actually realise it was you that sent the PR for this feature. Awesome job 👍

**Comment by jtmthf** [comment]
@leebenson Specifically I meant that you have `bz` instead of `br` which will result in gzip encoding always being returned.

For the current resolution process, Koa has a nice utility method `ctx.acceptsEncoding(encodings: ...string)` that returns the best match encoding between the request and what the server supports including quality weighting for example if the request included `Accept-Encoding: br;q=1.0, gzip;q=0.8, *;q=0.1`. Right now the brotli version is sent even if it has a lower quality weight than gzip which is technically not the best behavior, but not incorrect either.

In the tests, the encoding fixture is smallest for the uncompressed file followed by brotli and then gzip. This only happens because the input file is 18 bytes making it near incompressible with these algorithms. I think the behavior for now is good enough because a marginally larger file should only be sent for extremely small files and explicitly handling this case would result in extra disk reads.

**Comment by leebenson** [comment]
Ah sorry @jtmthf, my bad - I totally missed that. Swapping that out for the corrected `br` does indeed return the correct Brotli version. What was throwing me off was that Chrome testing seemed to confirm that only the gzip was being loaded. But that might be because we're using `immutable: true` in ReactQL for production static assets.

I'll go ahead and close this-- my goof.

**Comment by jtmthf** [comment]
@leebenson It happens. Anyways I looked into why chrome was not retrieving the brotli assets and it's because brotli is https only. Here is the relevant chromium issue https://bugs.chromium.org/p/chromium/issues/detail?id=452335

**Comment by leebenson** [comment]
Good to know. I saw the 'https only' blurb in some cursory Brotli research, but was surprised to see Chrome was still advertising the header on plain http connections:

<img width="1046" alt="screen shot 2017-05-31 at 09 05 55" src="https://cloud.githubusercontent.com/assets/719722/26621953/8dd3f51c-45e0-11e7-909e-44aed1536f9b.png">

**Comment by leebenson** [comment]
@jtmthf - re-opening this, because there seems to be an issue when Accept-Encoding is:

`Accept-Encoding: gzip, deflate, sdch, br`

(As extracted from Chrome)

e.g.

Using _just_ `gzip, br` (in any order):

<img width="960" alt="screen shot 2017-06-05 at 13 46 46" src="https://cloud.githubusercontent.com/assets/719722/26784438/7f0bf944-49f5-11e7-87a8-171c232b5df3.png">

But with the full Chrome header (`gzip, deflate, sdch, br`):

<img width="970" alt="screen shot 2017-06-05 at 13 47 39" src="https://cloud.githubusercontent.com/assets/719722/26784452/9e5ea468-49f5-11e7-873e-5b36efcaf466.png">

The issue seems to be `deflate` - removing it or replacing it with anything else works fine.

Am I missing something, or is this is a bug?

**Comment by nickhstr** [comment]
I've run into the same issue as @leebenson
Does 'deflate' need to be included in ctx.acceptEncodings()?

**Comment by bredthau** [comment]
I too have run into this issue last weekend. Wanting to get it to work I spent some time analysing the issue. 

First of all as @nickhstr mentioned 'deflate' shouldn't be included in `ctx.acceptEncodings()`. What is the point of checking whether deflate would be a better match when the library doesn't provide an option for serving deflate compressed data. The problem is that chrome sends `br` as the last entry of accepted encodings and `ctx.acceptEncodings()` seems to process the encodings in the order specified in the header (at least in the absense of priority specifications), thus always matching `deflate` instead of `br`.

Changing this however totally broke my website: The `type()` function for setting the correct MIME-Type in the face of encryption only deals with `.gz`, which means that `.br` files will be served as `application/octet-stream`, which chrome doesn't like to much for html files (which it always tried to download) or css files (which weren't applied correctly). Besides this problem the type function might also set the wrong MIME-Type when trying to serve actual .gz files, so the correct fix is to only remove the outer file extension when actually using the appropriate compression algorithm.

Having fixed both of these issues it works correctly. If there is interest I could provide a patch for this, however there is still a small caveat I couldn't fix: Fixing the MIME-Type leads to the Unittests for brotli failing with a timeout. I haven't looked too far into it, but it seems that the testing framework doesn't comprehend brotli responses for text content.

**Comment by leebenson** [comment]
Definite interest here for a patch, @bredthau. If you'd be so kind as to submit a PR, that might be enough to get the attention of maintainers to figuring out the test framework issue.
